### PR TITLE
use file_system as file watcher

### PR DESCRIPTION
**Pull request by falood**
I renamed the file watcher `exfswatch` to `file_system`, make it works under a normal API.
Hope this pr is helpful for migrating to the new package.

Also thank you for the awesome `cortex` ❤️

### CODE REVIEW

**Comment by wpcarro** [comment]
@falood happy to switch dependencies to `file_system`.

Open to merging a PR that swaps the existing `exfswatch` calls to `file_system` calls, but I'm not sure we're interested in the architecture change that moves file logic from `FileWatcher` -> `Controller`.

**Comment by falood** [comment]
To keep a standalone `FileWatcher` will make message sent one more time, so I merged the logic to `Controller`.
If you think it's better to keep it, I'll modify my pr 🙂

**Comment by wpcarro** [comment]
@falood let's keep `FileWatcher` in place at the moment and we'll merge that PR.

**Comment by falood** [comment]
@wpcarro updated my pr 🙂

**Pull request merged**
